export const BACKGROUND_COLORS = {
	TRIVIA: '#E1DFDF',
	MODAL: 'rgba(0,0,0,0.7)',
	MODIFIED_PRESSABLE: '#d3d3e6',
	MENU_ITEM: '#dadaeb',
	ANSWER: '#E3D8D8'
} 

export const UNIQUE_COLORS = {
	MENU_ITEM_PRESSED: '#b7b7d3',
	ANSWER_BORDER: '#DDC9C9',
}

export const COMMON_COLORS = {
	DEFAULT: '#cfcdcd',
	BLACK: '#000',
	WHITE: '#FFF',
	GREY: 'grey',
	LIGHT_GREY: '#E0E0E0',
	MIDDLE_GREY: '#bebcbc',
	DARK_GREY: '#b1abab',
	VERY_DARK_GREY: '#958d8d',
	BLUE: '#0096C7',
	DARK_BLUE: '#0077B6',
	VERY_DARK_BLUE: '#023E8A',
	LIGHT_BLUE: '#00B4D8',
	VERY_LIGHT_BLUE: '#48CAE4'
}